MyStore/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from . import views

admin.site.site_header='MyStore'
admin.site.index_title = 'Admin Panel'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('account/',include('accounts.urls')),
    path('',include('store.urls')),
    path('api/',include('api.urls')),
    path('auth/',include('djoser.urls')),
    path('auth/',include('djoser.urls.jwt')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from accounts import views

app_name = 'accounts'

urlpatterns = [
	path('login',views.staff_login,name='login'),
	path('logout',views.staff_logout,name='logout'),
	path('register',views.staff_register,name='register'),
	# path('edit/staff',views.edit_staff_account,name='edit_staff_account'),
]

api/urls.py
from django.urls import path
from . import views

from rest_framework_nested import routers


############## API URL  ######################

router = routers.DefaultRouter()
router.register('collections', views.CollectionViewSet)
router.register('products', views.ProductViewSet)
router.register('orders', views.OrderViewSet)
router.register('items-1', views.OrderItemViewSet)
router.register('staff', views.StaffViewSet)


orders_router = routers.NestedDefaultRouter(router, 'orders',lookup='order')
orders_router.register('items', views.GetOrderItemViewSet,basename='order-items')


urlpatterns = router.urls + orders_router.urls


# urlpatterns=[

# ]

store/urls.py
from django.urls import path
from store import views


app_name='store'

urlpatterns=[
	path('dashboard/',views.dashboard,name='dashboard'),
	path('collection/',views.add_collection,name='collection'),
	path('collection/<int:pk>/update',views.update_collection,name='update_collection'),
	path('collection/<int:pk>/delete',views.delete_collection,name='delete_collection'),

	path('products/',views.all_product,name='products'),
	path('product/',views.add_product,name='product'),
	path('product/<str:slug>/update',views.update_product,name='update_product'),
	path('product/<str:slug>/delete',views.delete_product,name='delete_product'),

	
	path('order/add/',views.add_product_to_order,name='add_product_to_order'),
	path('order/product/<int:pk>/update',views.update_order_product,name='update_order_product'),
	path('ordered/product/',views.ordered,name='ordered'),
	path('order/all/',views.all_order,name='orders'),
	path('order/cancel/',views.cancel_order,name='cancel_order'),
	path('order/<str:pk>/delete',views.delete_order,name='delete_order'),

	path('load/product',views.load_product,name='load_product'),
	path('load/price',views.load_price,name='load_price'),

	path('print/receipt',views.generate_receipt,name='receipt'),

	path('edit/staff',views.edit_staff_account,name='edit_staff_account'),
	

]

templates/Dashboard/includes/_dashboard.html
 <h1 class="mt-4">Dashboard</h1>
                        <ol class="breadcrumb mb-4">
                            <li class="breadcrumb-item active">Dashboard</li>
                        </ol>
                        <!-- Display Content -->
                        <div class="row">
                            <div class="col-xl-3 col-md-6">
                                <div class="card bg-primary text-white mb-4">
                                    <div class="card-body">Primary Card</div>
                                    <div class="card-footer d-flex align-items-center justify-content-between">
                                        <a class="small text-white stretched-link" href="#">View Details</a>
                                        <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xl-3 col-md-6">
                                <div class="card bg-warning text-white mb-4">
                                    <div class="card-body">Warning Card</div>
                                    <div class="card-footer d-flex align-items-center justify-content-between">
                                        <a class="small text-white stretched-link" href="#">View Details</a>
                                        <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xl-3 col-md-6">
                                <div class="card bg-success text-white mb-4">
                                    <div class="card-body">Success Card</div>
                                    <div class="card-footer d-flex align-items-center justify-content-between">
                                        <a class="small text-white stretched-link" href="#">View Details</a>
                                        <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xl-3 col-md-6">
                                <div class="card bg-danger text-white mb-4">
                                    <div class="card-body">Danger Card</div>
                                    <div class="card-footer d-flex align-items-center justify-content-between">
                                        <a class="small text-white stretched-link" href="#">View Details</a>
                                        <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xl-6">
                                <div class="card mb-4">
                                    <div class="card-header">
                                        <i class="fas fa-chart-area me-1"></i>
                                        Area Chart Example
                                    </div>
                                    <div class="card-body"><canvas id="myAreaChart" width="100%" height="40"></canvas></div>
                                </div>
                            </div>
                            <div class="col-xl-6">
                                <div class="card mb-4">
                                    <div class="card-header">
                                        <i class="fas fa-chart-bar me-1"></i>
                                        Bar Chart Example
                                    </div>
                                    <div class="card-body"><canvas id="myBarChart" width="100%" height="40"></canvas></div>
                                </div>
                            </div>
                        </div>

templates/Dashboard/includes/_footer.html
<footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid px-4">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; MyStore 2022</div>
                            <div>
                                <a href="#">Privacy Policy</a>
                                &middot;
                                <a href="#">Terms &amp; Conditions</a>
                            </div>
                        </div>
                    </div>
                </footer>

templates/Dashboard/includes/_sidebar.html
<!--  <style type="text/css">
     .nav-link{
        color: white !important;
     }
 </style> -->
 <div id="layoutSidenav_nav">
    <nav class="sb-sidenav accordion sb-sidenav-dark " id="sidenavAccordion">
        <div class="sb-sidenav-menu text-white">
            <div class="nav text-white" style="color:white !important;">
                <div class="sb-sidenav-menu-heading " >Core</div>
                <a class="nav-link text-white" href="{% url 'store:dashboard' %}">
                    <div class="sb-nav-link-icon "><i class="fa fa-tachometer"></i></div>
                    Dashboard
                </a>
                <div class="sb-sidenav-menu-heading ">SHOP OPERATION</div>
                <a class="nav-link collapsed" id="store" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                    <div class="sb-nav-link-icon"><i class="fa fa-columns"></i></div>
                    Store
                    <div class="sb-sidenav-collapse-arrow"><i class="fa fa-angle-down"></i></div>
                </a>
                <div class="collapse" id="collapseLayouts" aria-labelledby="Store" data-bs-parent="#sidenavAccordion">
                    <nav class="sb-sidenav-menu-nested nav">
                        <a class="nav-link collapsed" id="collection" href=""data-bs-toggle="collapse" data-bs-target="#collapseCollection" aria-expanded="false" aria-controls="collapseCollection">
                            <div class="sb-nav-link-icon"><i class="fa fa-check"></i></div>
                            Collection
                            <div class="sb-sidenav-collapse-arrow"><i class="fa fa-angle-down"></i></div>
                        </a>

                        <div class="collapse" id="collapseCollection" aria-labelledby="Collection" >
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" href="{% url 'store:collection' %}">Add Collection</a>
                                <!-- <a class="nav-link" href="{% url 'store:products' %}">All Product</a> -->
                            </nav>
                        </div>


                        <a class="nav-link collapsed" id="product" href=""data-bs-toggle="collapse" data-bs-target="#collapseProduct" aria-expanded="false" aria-controls="collapseProduct">
                            <div class="sb-nav-link-icon"><i class="fa fa-check"></i></div>
                            Product
                            <div class="sb-sidenav-collapse-arrow"><i class="fa fa-angle-down"></i></div>
                        </a>

                        <div class="collapse" id="collapseProduct" aria-labelledby="Product" >
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" href="{% url 'store:product' %}">Add Product</a>
                                <a class="nav-link" href="{% url 'store:products' %}">All Product</a>
                            </nav>
                        </div>

                        <!-- Order Product -->
                        <a class="nav-link collapsed" id="product" href=""data-bs-toggle="collapse" data-bs-target="#collapseOrderProduct" aria-expanded="false" aria-controls="collapseOrderProduct">
                            <div class="sb-nav-link-icon"><i class="fa fa-check"></i></div>
                            Order Product
                            <div class="sb-sidenav-collapse-arrow"><i class="fa fa-angle-down"></i></div>
                        </a>

                        <div class="collapse" id="collapseOrderProduct" aria-labelledby="OrderProduct" >
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" href="{% url 'store:add_product_to_order' %}">Order Product</a>
                                <a class="nav-link" href="{% url 'store:orders' %}">All Order </a>
                            </nav>
                        </div>
                    </nav>
                </div>
                <div class="sb-sidenav-menu-heading ">Store Addons</div>
                <a class="nav-link" href="{% url 'store:edit_staff_account' %}">
                    <div class="sb-nav-link-icon"><i class="fa fa-users"></i></div>
                    Edit Staff Account
                </a>
                <a class="nav-link" href="{% url 'accounts:logout' %}">
                    <div class="sb-nav-link-icon"><i class="fa fa-sign-out"></i></div>
                    Logout
                </a>
                <!-- <a class="nav-link" href="tables.html">
                    <div class="sb-nav-link-icon"><i class="fa fa-table"></i></div>
                    Tables
                </a> -->
            </div>
        </div>
        <div class="sb-sidenav-footer" style="text-transform: capitalize;">
            <div class="small">Logged in as:</div>
            {{request.user.username}}
        </div>
    </nav>
</div>

templates/Dashboard/includes/_topbar.html
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark ">
            <!-- Navbar Brand-->
            <a class="navbar-brand ps-3" href="{% url 'store:dashboard' %}">MyStore</a>
            <!-- Sidebar Toggle-->
            <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fa fa-bars"></i></button>
            <!-- Navbar Search-->
            <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
                <div class="input-group">
                    <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
                    <button class="btn btn-light" id="btnNavbarSearch" type="button"><i class="fa fa-search"></i></button>
                </div>
            </form>
            <!-- Navbar-->
            <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4 ">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fa fa-user fa-fw"></i></a>
                    <ul class="dropdown-menu dropdown-menu-end text-dark" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url 'store:edit_staff_account' %}">Settings</a></li>
                        <li><a class="dropdown-item" href="#!">Activity Log</a></li>
                        <li><hr class="dropdown-divider" /></li>
                        <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a></li>
                    </ul>
                </li>
            </ul>
        </nav>