MyStore/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from . import views

admin.site.site_header='MyStore'
admin.site.index_title = 'Admin Panel'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('account/',include('accounts.urls')),
    path('',include('store.urls')),
    path('api/',include('api.urls')),
    path('auth/',include('djoser.urls')),
    path('auth/',include('djoser.urls.jwt')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

api/urls.py
from django.urls import path
from . import views

from rest_framework_nested import routers


############## API URL  ######################

router = routers.DefaultRouter()
router.register('collections', views.CollectionViewSet)
router.register('products', views.ProductViewSet)
router.register('orders', views.OrderViewSet)
router.register('items-1', views.OrderItemViewSet)
router.register('staff', views.StaffViewSet)


orders_router = routers.NestedDefaultRouter(router, 'orders',lookup='order')
orders_router.register('items', views.GetOrderItemViewSet,basename='order-items')


urlpatterns = router.urls + orders_router.urls


# urlpatterns=[

# ]

store/urls.py
from django.urls import path
from store import views


app_name='store'

urlpatterns=[
	path('dashboard/',views.dashboard,name='dashboard'),
	path('collection/',views.add_collection,name='collection'),
	path('collection/<int:pk>/update',views.update_collection,name='update_collection'),
	path('collection/<int:pk>/delete',views.delete_collection,name='delete_collection'),

	path('products/',views.all_product,name='products'),
	path('product/',views.add_product,name='product'),
	path('product/<str:slug>/update',views.update_product,name='update_product'),
	path('product/<str:slug>/delete',views.delete_product,name='delete_product'),

	
	path('order/add/',views.add_product_to_order,name='add_product_to_order'),
	path('order/product/<int:pk>/update',views.update_order_product,name='update_order_product'),
	path('ordered/product/',views.ordered,name='ordered'),
	path('order/all/',views.all_order,name='orders'),
	path('order/cancel/',views.cancel_order,name='cancel_order'),
	path('order/<str:pk>/delete',views.delete_order,name='delete_order'),

	path('load/product',views.load_product,name='load_product'),
	path('load/price',views.load_price,name='load_price'),

	path('print/receipt',views.generate_receipt,name='receipt'),

	path('edit/staff',views.edit_staff_account,name='edit_staff_account'),
	

]

store/models.py
from django.db import models
from django.conf import settings
from django.core.validators import MinValueValidator
from django.utils.text import slugify

import secrets

# Create your models here.
class Staff(models.Model):

	GENDER_CHOICES_MALE = 'M'
	GENDER_CHOICES_FEMALE = 'F'
	GENDER_CHOICES=[
	(GENDER_CHOICES_MALE,'MALE'),
	(GENDER_CHOICES_FEMALE,'FEMALE'),
	]
	user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,related_name="staff")
	phone_number = models.CharField(max_length=20)
	gender = models.CharField(max_length=1,choices=GENDER_CHOICES)
	user_type = models.CharField(max_length=255,default='STAFF')
	shop_name = models.CharField(max_length=255)

	def __str__(self):

		return f'{self.user.username}'



class Collection(models.Model):
	title = models.CharField(max_length=255)

	def __str__(self):
		return f'{self.title}'

class Product(models.Model):
	product_id = models.CharField(max_length=255,primary_key=True)
	name = models.CharField(max_length=255,verbose_name='Product Name')
	description = models.TextField(verbose_name="Product Description")
	price = models.DecimalField(max_digits=8,decimal_places=2,validators=[MinValueValidator(1)])
	slug= models.SlugField()
	collection = models.ForeignKey(Collection, on_delete=models.CASCADE,related_name='products')
	quantity = models.PositiveSmallIntegerField(validators=[MinValueValidator(1)])
	at_created = models.DateTimeField(auto_now=True)
	at_updated = models.DateTimeField(auto_now_add=True)
	image= models.ImageField(upload_to='store/image',null=True,blank=True)
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT,null=True)

	def save(self,*args,**kwargs):
		while not self.product_id:
			product_id = 'PR_' + f'{secrets.token_hex(2)}'.upper()

			check_product_id = Product.objects.filter(product_id=product_id)

			if not check_product_id:
				self.product_id = product_id

		self.slug = slugify(self.name)

		super().save(*args,**kwargs)
		

	def __str__(self):
		return f'{self.name}'


class OrderItem(models.Model):

	collection = models.ForeignKey(Collection, on_delete=models.SET_NULL,null=True)
	product = models.ForeignKey(Product, on_delete=models.PROTECT)
	price = models.DecimalField(max_digits=8,decimal_places=2,validators=[MinValueValidator(1)])
	quantity = models.PositiveSmallIntegerField(validators=[MinValueValidator(1)])
	order = models.ForeignKey('Order', on_delete=models.CASCADE,related_name="orderitems")

	def __str__(self):
		return f'{self.product.name}'


class Order(models.Model):
	order_id = models.CharField(max_length=255,primary_key=True)
	total_price = models.DecimalField(max_digits=8,decimal_places=2,validators=[MinValueValidator(1)] , null=True)
	is_ordered = models.BooleanField(default=False)
	at_ordered = models.DateField(auto_now_add=True)
	items = models.ManyToManyField(OrderItem,related_name='items') 
	staff = models.ForeignKey(Staff, on_delete=models.SET_NULL,null=True)


	def save(self,*args,**kwargs):

		while not self.order_id:
			order_id = f'{secrets.token_hex(3)}'.upper()

			check_order_id = Order.objects.filter(order_id=order_id)

			if not check_order_id:

				self.order_id = order_id
		super().save(*args,**kwargs)


	def __str__(self):
		return f'{self.order_id}'




class OrderProduct(models.Model):
	order_id = models.CharField(max_length=255,primary_key=True)
	collection= models.ForeignKey(Collection, on_delete=models.PROTECT)
	product= models.ForeignKey(Product,on_delete=models.PROTECT)
	price = models.DecimalField(max_digits=8,decimal_places=2,validators=[MinValueValidator(1)])
	total_price = models.DecimalField(max_digits=8,decimal_places=2,validators=[MinValueValidator(1)])
	quantity = models.PositiveSmallIntegerField(validators=[MinValueValidator(1)])
	at_ordered = models.DateField(auto_now_add=True)


	def save(self,*args,**kwargs):

		while not self.order_id:
			order_id = f'#{secrets.token_hex(3)}'.upper()

			check_order_id = OrderProduct.objects.filter(order_id=order_id)

			if not check_order_id:

				self.order_id = order_id
		super().save(*args,**kwargs)


	def __str__(self):
		return f'{self.product.name}'
		

store/views.py
from django.db import transaction
from django.db.models import F,Q,ExpressionWrapper
from django.db.models.aggregates import Count,Sum
from django.contrib import messages
from django.conf import settings
from django.http import HttpResponseRedirect,JsonResponse,HttpResponse
from django.shortcuts import render,redirect
from django.utils.html import format_html

from fpdf import FPDF
from django.http import FileResponse


from store import forms,models
from accounts.models import User

# User = settings.AUTH_USER_MODEL

# Create your views here.

def dashboard(request):

	
	collections = models.Collection.objects.all()
	products = models.Product.objects.select_related('collection').all()

	complete = True
	pend = False

	completed_orders = models.Order.objects.filter(is_ordered=True)
	pending_orders = models.Order.objects.filter(is_ordered=False)



	context={
		'collections':collections,
		'products':products,
		'completed_orders':completed_orders,
		'pending_orders':pending_orders,
		'pend':pend,
		'complete':complete
	}
	return render(request,'store/dashboard.html',context)

def add_collection(request):

	products=None
	# product= models.Product.objects.values('id').distinct()
	collections= models.Collection.objects.all().annotate(product_assigned_to_collection=Count(F('products'))).distinct()
	form = forms.CollectionForm()

	collection_product = request.GET.get('collection_product')
	if request.method == 'GET' and collection_product != None :
		collection = request.GET.get('collection_product') if request.GET.get('collection_product') != None else ' '
		products = models.Product.objects.filter(collection__id=collection)

	if request.method == 'POST':
		form = forms.CollectionForm(data=request.POST)

		if form.is_valid():
			form.save()
			messages.success(request,'Collection Sucessfully Saved!')
			return HttpResponseRedirect('.')

		else:

			messages.error(request, 'Unable to Update Collection!')


	context={
				'form':form,
				'collections':collections,
				'products':products,
				'collection_product':collection_product
	}
	return render(request,'store/collection.html',context)


def update_collection(request,pk):

	verify = 'update'
	collection = models.Collection.objects.get(pk=pk)
	form = forms.CollectionForm(instance=collection)

	if request.method == 'POST':

		title = request.POST.get('title')

		collection.title = title

		collection.save()

		if collection:

			messages.success(request, 'Collection Updated Successfully!')
			return redirect('store:collection')
		else:

			messages.error(request, 'Unable to Update Collection!')

		return redirect('store:collection')

	context = {'form':form,'verify':verify}
	return render(request, 'store/collection.html',context)


def delete_collection(request,pk):

	collection = models.Collection.objects.get(pk=pk)

	if request.method == 'POST':

		collection.delete()

		if collection:

			messages.success(request, 'Collection Successfully Deleted!')
			return redirect('store:collection')
		else:

			messages.error(request, 'Unable to Update Collection!')

		return redirect('store:collection')


	context = {'obj':collection}
	return render(request, 'store/delete.html',context)


def all_product(request):

	products = models.Product.objects.select_related('collection').all()

	context={'products':products}
	return render(request, 'store/products.html',context)
	
def add_product(request):


	collections = models.Collection.objects.all()
	if request.method == 'GET':
		form = forms.ProductForm()

	elif request.method =='POST':
		with transaction.atomic():
			# Getting Collection From the Form
			collection_title = request.POST.get('collection')

			# Get or Create Collection
			product_collection,created = models.Collection.objects.get_or_create(title=collection_title)

			#  Getting the Product Info From the Form

			product_name = request.POST.get('name')
			product_description = request.POST.get('description')
			product_price = request.POST.get('price')
			product_quantity = request.POST.get('quantity')
			product_user = request.user

			if models.Product.objects.filter(name=product_name).exists():
				messages.warning(request,'Product Name Exist!')
				return HttpResponseRedirect('.')


			else:
				# Create a Product
				models.Product.objects.create(

					user = product_user,
					quantity = product_quantity,
					price = product_price,
					description = product_description,
					name = product_name,
					collection =  product_collection
				)
				messages.success(request, 'Product Saved Successfully!')

				return HttpResponseRedirect('.')

		
	context = {
				'form':form,
				'collections':collections
	}

	return render(request, 'store/product.html',context)


def update_product(request,slug):

	verify = 'update'
	collections = models.Collection.objects.all()
	product = models.Product.objects.get(slug=slug)
	collection_get = product.collection.title
	form = forms.ProductForm(instance=product)

	if request.method == 'POST':

		# Get Product
		product_name = request.POST.get('name')
		product_description = request.POST.get('description')
		product_price = request.POST.get('price')
		product_quantity = request.POST.get('quantity')

		# Get Collection
		collection = request.POST.get('collection')
		product_collection,created = models.Collection.objects.get_or_create(title=collection.strip())

		# Update Product Instance
		product.name = product_name
		product.description = product_description
		product.price = product_price
		product.quantity = product_quantity
		product.collection = product_collection
		product.save()

		if product:
			messages.success(request, 'Product Updated Successfully!')
			return redirect('store:products')
		else:
			messages.error(request, 'Product Unable to Updated!')
		
		return redirect('store:products')


	context = {
				'form':form,
				'collections':collections,
				'verify':verify,
				'collection':collection_get}

	return render(request,'store/product.html',context)


def delete_product(request,slug):

	
	product = models.Product.objects.get(slug=slug)

	if request.method == 'POST':

		product.delete()

		if product:

			messages.success(request, 'Product Successfully Deleted!')
			return redirect('store:products')
		else:

			messages.error(request, 'Unable to Update Product!')

		return redirect('store:products')


	context = {'obj':product}
	return render(request, 'store/delete.html',context)

def all_order(request):
	complete = True
	pend = False

	pending = request.GET.get('pending') if request.GET.get('pending') != None else ' '
	if request.GET.get('pending_orders') and pending != None:
		pending_orders = models.Order.objects.filter(is_ordered=pending)
	else:
		pending_orders = models.Order.objects.filter(is_ordered=False)

	products=None
	# orders=None

	completed = request.GET.get('completed') if request.GET.get('completed') != None else ' '
	pending = request.GET.get('pending') if request.GET.get('pending') != None else ' '
	if request.GET.get('completed'):
		orders = models.Order.objects.prefetch_related('items').filter(Q(is_ordered=completed))

	elif request.GET.get('pending'):
		orders = models.Order.objects.prefetch_related('items').filter(Q(is_ordered=pending))

	else:
		orders=models.Order.objects.prefetch_related('items').all()

	order_product = request.GET.get('order_product')
	if request.method == 'GET' and order_product != None :
		order = request.GET.get('order_product') if request.GET.get('order_product') != None else ' '
		products = models.OrderItem.objects.select_related('collection','product')\
											.filter(pk=order)\
											.annotate(total_price=F('price')*F('quantity'))

	context={
			'orders':orders,
			'products':products,
			'order_product':order_product,
			'complete':complete,
			'pend':pend,
			}
	return render(request, 'store/allorders.html',context)
	


def add_product_to_order(request):


	form = forms.OrderItemForm()

	# Choosen Product
	order_id=request.session.get('order_id')
	products = models.OrderItem.objects.filter(order_id=order_id).annotate(total_price=F('price')*F('quantity'))

	total_price = products.aggregate(overall_price=Sum(F('total_price'))) 


	try:
		request.session['total_price'] = str(total_price['overall_price'])
	except:
		pass


	if request.method == 'POST':

		# Get request
		collection_id = request.POST.get('collection')
		collection = models.Collection.objects.get(id=collection_id)
		quantity = request.POST.get('quantity')
		product_id= request.POST.get('product')
		product = models.Product.objects.get(pk=product_id)
		price = request.POST.get('price')

		order,created = models.Order.objects.get_or_create(order_id=order_id)

		request.session['order_id'] = order.order_id


		if product.quantity == 0:
			product_message = format_html('<b>{}</b> is all sold out!',f'{product.name} ')
			messages.warning(request, product_message )

		elif models.OrderItem.objects.filter(product=product,order=order).exists():
			order = models.OrderItem.objects.get(product=product)

			order.quantity +=int(quantity)

			product.quantity -= int(quantity)
			product.save()

			order.save()
			return HttpResponseRedirect('.')
			
		else:

			order_items = models.OrderItem.objects.create(
			collection=collection,
			product = product,
			quantity= quantity,
			price = price,
			order = order
			)
			product.quantity -= int(quantity)
			product.save()

			order_items.save()
			messages.success(request, 'Product Added Successfully !')
			
			return HttpResponseRedirect('.')

			
	context= {'form':form,'products':products,'total_price':total_price,'order_id':order_id}

	return render(request, 'store/order.html',context)


def update_order_product(request,pk):

	verify = 'update'
	order_product = models.OrderItem.objects.get(pk=pk)
	form = forms.OrderItemForm(instance=order_product)

	if request.method == 'POST':

		collection_id = request.POST.get('collection')
		collection = models.Collection.objects.get(id=collection_id)
		quantity = request.POST.get('quantity')

store/templates/store/allorderproduct.html
{% extends 'Dashboard/base.html' %}


{% load static %}
{% block content %}

<h1 class="mt-4">All Order Product</h1>
<!-- Breadcrumbs -->
<nav aria-label="Page breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'store:dashboard' %}">Dashboard</a></li>
        <li class="breadcrumb-item"><a href="#">Store</a></li>
        <li class="breadcrumb-item"><a href="#">Product</a></li>
        <li class="breadcrumb-item active" aria-current="page">All Order Product</li>
    </ol>
</nav>
<hr>

<div class="row">
	{% include 'store/includes/messages.html' %}
	<div class="card mb-4">
		<div class="card-header">
            <i class="fa fa-table me-1"></i>
            All Ordered Product
        </div>
        <div class="card-body">
			<div class="table-responsive">
				<table class="table table-striped table-hover" id="table-data">
				  <caption>List of Ordered Products</caption>
				  <thead class="thead-dark">
				    <tr>
				      <th scope="col">Order ID</th>
				      <th scope="col">Product Name</th>
				      <th scope="col">Collection</th>
				      <th scope="col">Price</th>
				      <th scope="col">Quantity</th>
				      <th scope="col">Total Price</th>
				      <th scope="col">Action</th>
				    </tr>
				  </thead>
				  <tbody>
				  	{% for product in products %}
				    <tr>
				      <th scope="row">{{product.order_id}}</th>
				      <td>{{product.product.name}}</td>
				      <td>{{product.collection.title}}</td>
				      <td>{{product.price}}</td>
				      <td>{{product.quantity}}</td>
				      <td>{{product.total_price}}</td>
				      <td> 
						{% comment %} <a href="{% url 'store:delete_product' product.slug %}" class="btn btn-danger btn-sm">Delete</a>  {% endcomment %}
						<a href="{% url 'store:update_order_product' product.pk %}" class="btn btn-warning btn-sm">Update</a> 
					  </td>
				    </tr>
				    {% endfor %}
				  </tbody>
				</table>
			</div>
		</div>
	</div>
</div>



{% endblock content %}

store/templates/store/allorders.html
{% extends 'Dashboard/base.html' %}


{% load static %}
{% block content %}

<h1 class="mt-4">All Order Product</h1>
<!-- Breadcrumbs -->
<nav aria-label="Page breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'store:dashboard' %}">Dashboard</a></li>
        <li class="breadcrumb-item"><a href="#">Store</a></li>
        <li class="breadcrumb-item"><a href="{% url 'store:products' %}">Product</a></li>
        <li class="breadcrumb-item active" aria-current="page">All Order Product</li>
    </ol>
</nav>
<hr>

<div class="row">
	{% include 'store/includes/messages.html' %}
	<div class="card my-4">
		<div class="card-header">
            <i class="fa fa-table me-1"></i>
            All Ordered Product
        </div>
        <div class="card-body">
			<div class="table-responsive">
				<table class="table table-striped table-hover" id="table-data">
				  <caption>List of Ordered Products</caption>
				  <thead class="thead-dark">
				    <tr>
				      <th scope="col">Order ID</th>
				      <th scope="col">Products</th>
				      <th scope="col">Total Price</th>
				      <th scope="col">Order Status</th>
				      <th scope="col">Date Ordered</th>
				      <th scope="col">Action</th>

				    </tr>
				  </thead>
				  <tbody>
				  	{% for order in orders %}
				    <tr>
				      <th scope="row">{{order.order_id}}</th>
				      <span class="badge-bs badge-primary badge-pill">{{product.quantity}}</span>
				      <td width="60%">
				      		<ul class="list-group">
					      		<div class="row">
					      			{% for product in order.items.all %}
					      			<div class="col-md-6">
						      			<a href="{% url 'store:orders' %}?order_product={{product.pk}}">
							      			<li class="list-group-item d-flex justify-content-between align-items-center">
								      		    {{product.product.name}}

								      		    <span class="badge badge-success badge-pill bg-success">
								      		    	{% if product.quantity == 1%}{{product.quantity}} Quantity {% else %}{{product.quantity}} Quantities {% endif%}
								      			</span>
							      		  	</li>
						      		  	</a>
					      			</div>
					      			 {% endfor %}
					      		</div>
				      		</ul>
				      </td>
				      <td>N{{order.total_price}}</td>
				      <td>
				      	{% if order.is_ordered == False %}
				      	<span class="badge badge-danger badge-pill bg-danger">Pending</span>
				      	{% else %}
				      	<span class="badge badge-bs-success badge-pill bg-success">Complete</span>
				      	{% endif %}

				      </td>
				      <td>{{order.at_ordered}}</td>
				      <td><a class="btn btn-danger btn-sm" href="{% url 'store:delete_order' order.pk %}">Delete</a></td>
				      
				    </tr>
				    {% endfor %}
				  </tbody>
				</table>
			</div>
		</div>
	</div>
</div>

{% if order_product %}

<div class="row">
	 <div class="card-body">
			<div class="table-responsive">
				<table class="table table-striped table-hover" id="table-data">
				  <caption>List of Ordered Products</caption>
				  <thead class="thead-dark">
				    <tr>
				      <th scope="col">Order ID</th>
				      <th scope="col">Product Name</th>
				      <th scope="col">Collection</th>
				      <th scope="col">Price</th>
				      <th scope="col">Quantity</th>
				      <th scope="col">Total Price</th>
				      <th scope="col">Action</th>
				    </tr>
				  </thead>
				  <tbody>
				  	{% for product in products %}
				    <tr>
				      <th scope="row">{{product.order.order_id}}</th>
				      <td>{{product.product.name}}</td>
				      <td>{{product.collection.title}}</td>
				      <td>{{product.price}}</td>
				      <td>{{product.quantity}}</td>
				      <td>{{product.total_price}}.00</td>
				      <td> 
						{% comment %} <a href="{% url 'store:delete_product' product.slug %}" class="btn btn-danger btn-sm">Delete</a>  {% endcomment %}
						<a href="{% url 'store:update_order_product' product.pk %}" class="btn btn-warning btn-sm">Update</a> 
					  </td>
				    </tr>
				    {% endfor %}
				  </tbody>
				</table>
			</div>
		</div>
</div>
{% endif %}


{% endblock content %}

store/templates/store/order.html
{% extends 'Dashboard/base.html' %}

{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<style type="text/css">
	.form-group{
		margin-top: 5px;
		margin-bottom: 5px;
	}
</style>

<h1 class="mt-4">{% if verify == 'update' %} Update Order Product {% else %} Add Order Product {% endif %}</h1>
<!-- Breadcrumbs -->
<nav aria-label="Page breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'store:dashboard' %}">Dashboard</a></li>
        <li class="breadcrumb-item"><a href="#store">Store</a></li>
        <li class="breadcrumb-item"><a href="{% url 'store:products' %}">Product</a></li>
        <li class="breadcrumb-item active" aria-current="page">Order Product</li>
    </ol>
</nav>
<hr>

<div class="row">
	<form method="POST" id="order_product" data-products-url="{% url 'store:load_product' %}">
		{% csrf_token %}
		<div class="container">
			<div class="row ">
				<div class="col-md-5 bg-white p-4">
					{% include 'store/includes/messages.html' %}
					<div class="form-group">
						{{form.collection|as_crispy_field}}
					</div>

					<div class="form-group">
						{{form.product|as_crispy_field}}
					</div>

					<div class="form-group">
						{{form.price|as_crispy_field}}
						<input type="text" name="" id="price1" class="form-control" value="{% if verify == 'update' %} {{form.instance.price}} {% endif %}" readonly>

					</div>

					<div class="form-group">
						{{form.quantity|as_crispy_field}}
					</div>

					<div class="form-group" >
						<p style="font-weight: bolder;" name="total_price">Total: <i id=total></i> </p>
					</div>

					<button class="btn btn-dark mt-3" type="submit">{% if verify == 'update' %} Update Product {% else %} Add Product {% endif %}</button>

				</div>

				<div class="col-md-2">

				</div>

				<div class="col-md-5">
					{% if order_id %}
					<table class="table ">
						<thead>
							<tr>
								<th>Collection</th>
								<th>Product</th>
								<th>Price</th>
								<th>Quantity</th>
								<th>Total Price</th>
							</tr>
						</thead>
						<tbody>
							{% for product in products %}
							<tr>
								<td>{{product.collection.title}}</td>
								<td>{{product.product.name}}</td>
								<td>N{{product.price}}</td>
								<td>{{product.quantity}}</td>
								<td>N{{product.total_price}}</td>
							</tr>
							{% endfor %}
							<tr class="bg-dark text-white">
								<td colspan="5" style="text-align:right"><b>Total: </b>N{{total_price.overall_price}}</td>
							</tr>
						</tbody>
					</table>
					<div>
						Action: 
						<select name="order_action" id="order_action">
							<option value="Order Product"> Order Product</option>
							<option value="Cancel Order Product"> Cancel Order Product</option>
						</select>
					</div>
					<center><a href="{% url 'store:ordered' %}" class="btn btn-light">Order Product</a></center>
					<center><a href="{% url 'store:cancel_order' %}" class="btn btn-light">Cancel Order Product</a></center>
					{% endif %}
				</div>

			</div>
		</div>

	</form>
</div>


	<!-- Jquery Plugin Api -->
    <script src="{% static 'jquery/jquery-3.2.1.min.js' %}"></script>
    <!-- <script src="{% static 'js/jquery-2.1.1.min.js' %}"></script> -->

    <!-- <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script> -->

<script>

	$("#id_collection").change(function (){

		const url = $("#order_product").attr("data-products-url"); // Getting the load cites url
		const collectionid= $(this).val(); // Get the selected collection id from the html input
		
		$.ajax({
			url: url,
			data: {
				'collection_id':collectionid,  // add the collection id to the GET parameters
				'product_id':$("#id_product").val()
			},
			success: function (data){  // `data` is the return of the `load_product` view function
				
				// replace the contents of the product input with the data that came from the server
				
				$("#id_product").html(data)

				// let html_data = '<option value="">--------</option>'

				// data.forEach(function (product) {

				// 	html_data += `<option value="${product.id}">${product.name}</option>`
				// });

				// $("#id_product").html(html_data)
			}
		});

	});

	$("#id_product").change(function (){

		const url = "{% url 'store:load_price' %}"; // Getting the load cites url
		const productid= $(this).val(); // Get the selected collection id from the html input
		
		$.ajax({
			url: url,
			data: {
				'product_id':productid // add the collection id to the GET parameters
			},
			success: function (data){  // `data` is the return of the `load_product` view function
				
				// replace the contents of the product input with the data that came from the server
				
				// $("#id_product").html(data)

				let html_data =''  

				data.forEach(function (price) {

					html_data += `${price.price}`
				});

				$("#price").val(html_data)
				$("#price1").val(html_data )
			}
		});

	});

	$('#quantity').on('change',function(){
		var total = $('#price').val() * this.value
		$('#total').html(total)
	})

	$('#order_action').on('click',function(){
	})
	
</script>


{% endblock content %}

store/templates/store/product_load.html
<option value="">---------</option>
{% for product in products %}
<option value="{{ product.pk }}">{{ product.name }}</option>
{% endfor %}